# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_streaming.proto',
  package='sensorstreaming',
  syntax='proto3',
  serialized_options=b'\n io.grpc.examples.sensorstreamingB\017SensorStreamingP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16sensor_streaming.proto\x12\x0fsensorstreaming\"M\n\x16\x43\x61meraStreamingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x12\n\ndataLength\x18\x02 \x01(\x05\x12\x11\n\ttimeStamp\x18\x03 \x01(\r\"*\n\x17\x43\x61meraStreamingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32|\n\x0fSensorStreaming\x12i\n\x12StreamCameraSensor\x12\'.sensorstreaming.CameraStreamingRequest\x1a(.sensorstreaming.CameraStreamingResponse\"\x00\x42;\n io.grpc.examples.sensorstreamingB\x0fSensorStreamingP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CAMERASTREAMINGREQUEST = _descriptor.Descriptor(
  name='CameraStreamingRequest',
  full_name='sensorstreaming.CameraStreamingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='sensorstreaming.CameraStreamingRequest.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataLength', full_name='sensorstreaming.CameraStreamingRequest.dataLength', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='sensorstreaming.CameraStreamingRequest.timeStamp', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=120,
)


_CAMERASTREAMINGRESPONSE = _descriptor.Descriptor(
  name='CameraStreamingResponse',
  full_name='sensorstreaming.CameraStreamingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='sensorstreaming.CameraStreamingResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['CameraStreamingRequest'] = _CAMERASTREAMINGREQUEST
DESCRIPTOR.message_types_by_name['CameraStreamingResponse'] = _CAMERASTREAMINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraStreamingRequest = _reflection.GeneratedProtocolMessageType('CameraStreamingRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAMERASTREAMINGREQUEST,
  '__module__' : 'sensor_streaming_pb2'
  # @@protoc_insertion_point(class_scope:sensorstreaming.CameraStreamingRequest)
  })
_sym_db.RegisterMessage(CameraStreamingRequest)

CameraStreamingResponse = _reflection.GeneratedProtocolMessageType('CameraStreamingResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAMERASTREAMINGRESPONSE,
  '__module__' : 'sensor_streaming_pb2'
  # @@protoc_insertion_point(class_scope:sensorstreaming.CameraStreamingResponse)
  })
_sym_db.RegisterMessage(CameraStreamingResponse)


DESCRIPTOR._options = None

_SENSORSTREAMING = _descriptor.ServiceDescriptor(
  name='SensorStreaming',
  full_name='sensorstreaming.SensorStreaming',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamCameraSensor',
    full_name='sensorstreaming.SensorStreaming.StreamCameraSensor',
    index=0,
    containing_service=None,
    input_type=_CAMERASTREAMINGREQUEST,
    output_type=_CAMERASTREAMINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENSORSTREAMING)

DESCRIPTOR.services_by_name['SensorStreaming'] = _SENSORSTREAMING

# @@protoc_insertion_point(module_scope)
